class Currency{
  final int id;
  final String currency;
  final String symbol;
  final String country;
  bool isSelected = false;
  Currency({required this.id,required this.currency, required this.symbol, required this.country});
  
  static List<Currency> get currencies{
    final List<Map<String,dynamic>> json = [
      {"id":1,  "currency": "USD", "symbol": "\$","country":"United States","isSelected":false},
      {"id":2,"currency": "CAD", "symbol": "CA\$" , "country":"Canada"},
      {"id":3,"currency": "EUR", "symbol": "€","country":"Euro"},

      {"id":4,"currency": "AFN", "symbol": "Af","country":"Afghani"},
      {"id":5,"currency": "ALL", "symbol": "ALL", "country" : "Albanian Lek"},
      {"id":6,"currency": "ALL", "symbol": "ALL", "country" : "Albanian Lek"},
      {"id":7,"currency": "AMD", "symbol": "AMD", "country":"Armenian Dram"},
      {"id":8,"currency": "ARS", "symbol": "AR\$" , "country":"Argentine peso"},
      {"id":9,"currency": "AUD", "symbol": "AU\$", "country":"Austrailian Dollar"},
      {"id":10,"currency": "AZN", "symbol": "man.", "country":"Azerbaijan Manat"},
      {"id":11,"currency": "BAM", "symbol": "KM", "country":"Bosnia"},
      {"id":12,"currency": "BDT", "symbol": "Tk", "country":"Bangladeshi Taka"},
      {"id":13,"currency": "BGN", "symbol": "BGN", "country":"Bulgarian Lev"},
      {"id":14,"currency": "BHD", "symbol": "BD", "country":"Bahraini Dinar"},
      {"id":15,"currency": "BIF", "symbol": "FBu", "country":"Burundian Franc"},
      {"id":16,"currency": "BND", "symbol": "BN\$", "country":"Brunei Dollar"},
      {"id":17,"currency": "BOB", "symbol": "Bs", "country":"Boliviano"},
      {"id":18,"currency": "BRL", "symbol": "R\$", "country":"Brazilian Real"},
      {"id":19,"currency": "BWP", "symbol": "BWP", "country":"Botswana Pula"},
      {"id":20,"currency": "BYN", "symbol": "Br", "country":"Belerusian Rouble"},
      {"id":21,"currency": "BZD", "symbol": "BZ\$", "country":"Belize Dollar"},
      {"id":22,"currency": "CDF", "symbol": "CDF", "country":"Congolese Franc"},
      {"id":23,"currency": "CHF", "symbol": "CHF","country":"Swiss Franc"},
      {"id":24,"currency": "CLP", "symbol": "CL\$", "country":"chilean peso"},
      {"id":25,"currency": "CNY", "symbol": "CN¥", "country":"Chinese Yuan"},
      {"id":26,"currency": "COP", "symbol": "CO\$", "country":"Colombian peso"},
      {"id":27,"currency": "CRC", "symbol": "₡", "country":"Costa Rican Colon"},
      {"id":28,"currency": "CVE", "symbol": "CV\$", "country":"Cape Verdean Escudo"},
      {"id":29,"currency": "CZK", "symbol": "Kč", "country":"Czech Koruna "},
      {"id":30,"currency": "DJF", "symbol": "Fdj", "country":"Djiboutian Franc"},
      {"id":31,"currency": "DKK", "symbol": "Dkr", "country":"Danish Krone"},
      {"id":32,"currency": "DOP", "symbol": "RD\$", "country":"Dominican peso"},
      {"id":33,"currency": "DZD", "symbol": "DA", "country":"Algerian Dinar"},
      {"id":34,"currency": "EGP", "symbol": "EGP", "country":"Egyptian Pound"},
      {"id":35,"currency": "ERN", "symbol": "Nfk", "country":"Estern Caribbean Dollar"},
      {"id":36,"currency": "ETB", "symbol": "Br", "country":"Ethiopia Birr"},
      {"id":37,"currency": "GBP", "symbol": "£","country": "British Pound"},
      {"id":38,"currency": "GEL", "symbol": "GEL", "country":"Georgian Lari"},
      {"id":39,"currency": "GHS", "symbol": "GH₵", "country":"Ghananian Cedi"},
      {"id":40,"currency": "GNF", "symbol": "FG", "country":"Guinean France"},
      {"id":41,"currency": "GTQ", "symbol": "GTQ", "country":"Guatemalan Quetzal"},
      {"id":42,"currency": "HKD", "symbol": "HK\$", "country":"Hong kong dollar"},
      {"id":43,"currency": "HNL", "symbol": "HNL", "country":"Honduran Lempira"},
      {"id":44,"currency": "HRK", "symbol": "kn", "country":"Croatian Kuna"},
      {"id":45,"currency": "HUF", "symbol": "Ft", "country":"Hungarian Forint"},
      {"id":46,"currency": "IDR", "symbol": "Rp", "country":"Indonesian rupiah"},
      {"id":47,"currency": "ILS", "symbol": "₪", "country":"Israeli Shekel"},
      {"id":48,"currency": "INR", "symbol": "Rs", "country":"Indian Rupee"},
      {"id":49,"currency": "IQD", "symbol": "IQD", "country":"Iraqi dinar"},
      {"id":50,"currency": "IRR", "symbol": "IRR", "country":"Iranian Rial"},
      {"id":51,"currency": "ISK", "symbol": "Ikr", "country":"Icelandic Krona"},
      {"id":52,"currency": "JMD", "symbol": "J\$", "country":"Jamaican dollar"},
      {"id":53,"currency": "JOD", "symbol": "JD", "country":"Jordanian dinar"},
      {"id":54,"currency": "JPY", "symbol": "¥","country" : "Japanese Yen"},
      {"id":55,"currency": "KES", "symbol": "Ksh", "country":"Kenyan Shiling"},
      {"id":56,"currency": "KHR", "symbol": "KHR", "country":"Combodian riel"},
    
      {"id":57,"currency": "KRW", "symbol": "₩", "country":"South korean Won"},
      {"id":58,"currency": "KWD", "symbol": "KD", "country":"Kuwaiti dinar"},
      {"id":59,"currency": "KZT", "symbol": "KZT", "country":"Kazakhstani Tenge"},
      {"id":60,"currency": "LBP", "symbol": "L.L.", "country":"Lebanese Pound"},
      {"id":61,"currency": "LKR", "symbol": "SLRs", "country":"Sri Lankan Rupee"},
      // {"currency": "LTL", "symbol": "Lt"},
      // {"currency": "LVL", "symbol": "Ls"},
      // {"currency": "LYD", "symbol": "LD"},
      // {"currency": "MAD", "symbol": "MAD"},
      // {"currency": "MDL", "symbol": "MDL"},
      // {"currency": "MGA", "symbol": "MGA"},
      // {"currency": "MKD", "symbol": "MKD"},
      // {"currency": "MMK", "symbol": "MMK"},
      // {"currency": "MOP", "symbol": "MOP\$"},
      // {"currency": "MUR", "symbol": "MURs"},
      // {"currency": "MXN", "symbol": "MX\$"},
      // {"currency": "MYR", "symbol": "RM"},
      // {"currency": "MZN", "symbol": "MTn"},
      // {"currency": "NAD", "symbol": "N\$"},
      // {"currency": "NGN", "symbol": "₦"},
      // {"currency": "NIO", "symbol": "C\$"},
      // {"currency": "NOK", "symbol": "Nkr"},
      // {"currency": "NPR", "symbol": "NPRs"},
      // {"currency": "NZD", "symbol": "NZ\$"},
      // {"currency": "OMR", "symbol": "OMR"},
      // {"currency": "PAB", "symbol": "B/."},
      // {"currency": "PEN", "symbol": "S/."},
      // {"currency": "PHP", "symbol": "₱"},
      // {"currency": "PKR", "symbol": "PKRs"},
      // {"currency": "PLN", "symbol": "zł"},
      // {"currency": "PYG", "symbol": "₲"},
      // {"currency": "QAR", "symbol": "QR"},
      // {"currency": "RON", "symbol": "RON"},
      // {"currency": "RSD", "symbol": "din."},
      // {"currency": "RUB", "symbol": "RUB"},
      // {"currency": "RWF", "symbol": "RWF"},
      // {"currency": "SAR", "symbol": "SR"},
      // {"currency": "SDG", "symbol": "SDG"},
      // {"currency": "SEK", "symbol": "Skr"},
      // {"currency": "SGD", "symbol": "S\$"},
      // {"currency": "SOS", "symbol": "Ssh"},
      // {"currency": "SYP", "symbol": "SY£"},
      // {"currency": "THB", "symbol": "฿"},
      // {"currency": "TND", "symbol": "DT"},
      // {"currency": "TOP", "symbol": "T\$"},
      // {"currency": "TRY", "symbol": "TL"},
      // {"currency": "TTD", "symbol": "TT\$"},
      // {"currency": "TWD", "symbol": "NT\$"},
      // {"currency": "TZS", "symbol": "TSh"},
      // {"currency": "UAH", "symbol": "₴"},
      // {"currency": "UGX", "symbol": "USh"},
      // {"currency": "UYU", "symbol": "\$U"},
      // {"currency": "UZS", "symbol": "UZS"},
      // {"currency": "VEF", "symbol": "Bs.F"},
      // {"currency": "VND", "symbol": "₫"},
      // {"currency": "XAF", "symbol": "FCFA"},
      // {"currency": "XOF", "symbol": "CFA"},
      // {"currency": "YER", "symbol": "YR"},
      // {"currency": "ZAR", "symbol": "R"},
      // {"currency": "ZMK", "symbol": "ZK"},
      // {"currency": "ZWL", "symbol": "ZWL\$"}

    ];

    return json
    .map((c) {
        
       return Currency(id:c['id'], currency: c['currency'], symbol: c['symbol'], country: c['country']);}).toList();
  }
  }
  

